{"uuid": "858ce2ad-0327-4454-a7f9-52cfc3678d86", "befores": [{"name": "delete_register_user", "status": "broken", "statusDetails": {"message": "NameError: name 'base_data' is not defined\n", "trace": "  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/testcases/conftest.py\", line 79, in delete_register_user\n    del_sql = base_data[\"init_sql\"][\"delete_register_user\"]\n"}, "start": 1735665097774, "stop": 1735665097774}], "start": 1735665097774, "stop": 1735665097794}