{"name": "test_user_login[admin-admin123-dc5d385c6463466c9de6609cfc133557-True-200-\\u64cd\\u4f5c\\u6210\\u529f]", "status": "broken", "statusDetails": {"message": "KeyError: 'uid'", "trace": "self = <allure_pytest.listener.AllureListener object at 0x10e1ecc40>, item = <Function test_user_login[admin-admin123-dc5d385c6463466c9de6609cfc133557-True-200-\\u64cd\\u4f5c\\u6210\\u529f]>\n\n    @pytest.hookimpl(hookwrapper=True)\n    def pytest_runtest_setup(self, item):\n        if not self._cache.get(item.nodeid):\n            uuid = self._cache.push(item.nodeid)\n            test_result = TestResult(name=item.name, uuid=uuid, start=now(), stop=now())\n            self.allure_logger.schedule_test(uuid, test_result)\n    \n        yield\n    \n        uuid = self._cache.get(item.nodeid)\n        test_result = self.allure_logger.get_test(uuid)\n        for fixturedef in _test_fixtures(item):\n            group_uuid = self._cache.get(fixturedef)\n            if not group_uuid:\n                group_uuid = self._cache.push(fixturedef)\n                group = TestResultContainer(uuid=group_uuid)\n                self.allure_logger.start_group(group_uuid, group)\n            self.allure_logger.update_group(group_uuid, children=uuid)\n        params = item.callspec.params if hasattr(item, 'callspec') else {}\n    \n>       test_result.name = allure_name(item, params)\n\nvenv/lib/python3.8/site-packages/allure_pytest/listener.py:88: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nitem = <Function test_user_login[admin-admin123-dc5d385c6463466c9de6609cfc133557-True-200-\\u64cd\\u4f5c\\u6210\\u529f]>\nparameters = {'except_code': 200, 'except_msg': '操作成功', 'except_result': True, 'password': 'admin123', ...}\n\n    def allure_name(item, parameters):\n        name = escape_name(item.name)\n        title = allure_title(item)\n>       return title.format(**parameters) if title else name\nE       KeyError: 'uid'\n\nvenv/lib/python3.8/site-packages/allure_pytest/utils.py:112: KeyError"}, "start": 1735555070875, "stop": 1735555070875, "uuid": "c3e376e0-c6d9-4a49-aa22-1902445f3053", "labels": [{"name": "epic", "value": "针对单个接口测试"}, {"name": "story", "value": "用例--登陆用户"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登陆模块"}, {"name": "tag", "value": "singlesig"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_new_01_login"}, {"name": "subSuite", "value": "Test_new_User_login"}, {"name": "host", "value": "zhouqideMBP.lan"}, {"name": "thread", "value": "56213-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_new_01_login"}]}